// This file is auto-generated by cppwg; manual changes will be overwritten.

#ifndef pycells_HEADERS_HPP_
#define pycells_HEADERS_HPP_

// Includes
#include "AbstractMesh.hpp"
#include "MeshFactory.hpp"
#include "PottsMesh.hpp"

// Instantiate Template Classes
template class AbstractMesh<2, 2>;
template class AbstractMesh<3, 3>;
template class MeshFactory<PottsMesh<2>>;
template class MeshFactory<PottsMesh<3>>;
template class PottsMesh<2>;
template class PottsMesh<3>;

// Typedefs for nicer naming
namespace cppwg
{
    typedef AbstractMesh<2, 2> AbstractMesh_2_2;
    typedef AbstractMesh<3, 3> AbstractMesh_3_3;
    typedef MeshFactory<PottsMesh<2>> MeshFactory_PottsMesh_2;
    typedef MeshFactory<PottsMesh<3>> MeshFactory_PottsMesh_3;
    typedef PottsMesh<2> PottsMesh_2;
    typedef PottsMesh<3> PottsMesh_3;
} // namespace cppwg

#endif // pycells_HEADERS_HPP_
