// This file is auto-generated by cppwg; manual changes will be overwritten.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "PottsMesh.hpp"
#include <memory>
#include "MeshFactory.hpp"

#include "MeshFactory_PottsMesh_2.cppwg.hpp"

namespace py = pybind11;
typedef MeshFactory<PottsMesh<2>> MeshFactory_PottsMesh_2;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);

void register_MeshFactory_PottsMesh_2_class(py::module &m)
{
    py::class_<MeshFactory_PottsMesh_2, std::shared_ptr<MeshFactory_PottsMesh_2>>(m, "MeshFactory_PottsMesh_2")
        .def(py::init<>())
        .def("generateMesh",
            (::std::shared_ptr<PottsMesh<2>>(MeshFactory_PottsMesh_2::*)()) &MeshFactory_PottsMesh_2::generateMesh,
            " ")
    ;
}
