// This file is auto-generated by cppwg; manual changes will be overwritten.

#ifndef Node_3_hpp__cppwg_wrapper
#define Node_3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_Node_3_class(pybind11::module &m);
#endif // Node_3_hpp__cppwg_wrapper
