// This file is auto-generated by cppwg; manual changes will be overwritten.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
#include "Node.hpp"

#include "Node_2.cppwg.hpp"

namespace py = pybind11;
typedef Node<2> Node_2;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);

void register_Node_2_class(py::module &m)
{
    py::class_<Node_2, std::shared_ptr<Node_2>>(m, "Node_2")
        .def(py::init<>())
        .def(py::init<::std::vector<double>>(), py::arg("coords"))
        .def("GetIndex",
            (unsigned int(Node_2::*)() const) &Node_2::GetIndex,
            " ")
    ;
}
