// This file is auto-generated by cppwg; manual changes will be overwritten.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
#include "Node.hpp"

#include "Node_3.cppwg.hpp"

namespace py = pybind11;
typedef Node<3> Node_3;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);

void register_Node_3_class(py::module &m)
{
    py::class_<Node_3, std::shared_ptr<Node_3>>(m, "Node_3")
        .def(py::init<>())
        .def(py::init<::std::vector<double>>(), py::arg("coords"))
        .def("GetIndex",
            (unsigned int(Node_3::*)() const) &Node_3::GetIndex,
            " ")
    ;
}
