// This file is auto-generated by cppwg; manual changes will be overwritten.

#ifndef Node_2_hpp__cppwg_wrapper
#define Node_2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_Node_2_class(pybind11::module &m);
#endif // Node_2_hpp__cppwg_wrapper
