// This file is auto-generated by cppwg; manual changes will be overwritten.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <memory>
#include "PottsMesh.hpp"

#include "PottsMesh_2.cppwg.hpp"

namespace py = pybind11;
typedef PottsMesh<2> PottsMesh_2;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);

class PottsMesh_2_Overrides : public PottsMesh_2
{
public:
    using PottsMesh_2::PottsMesh;
    void Scale(double const factor) override
    {
        PYBIND11_OVERRIDE(
            void,
            PottsMesh_2,
            Scale,
            factor);
    }
};

void register_PottsMesh_2_class(py::module &m)
{
    py::class_<PottsMesh_2, PottsMesh_2_Overrides, std::shared_ptr<PottsMesh_2>, AbstractMesh<2>>(m, "PottsMesh_2")
        .def(py::init<>())
        .def("Scale",
            (void(PottsMesh_2::*)(double const)) &PottsMesh_2::Scale,
            " ", py::arg("factor"))
    ;
}
