// This file is auto-generated by cppwg; manual changes will be overwritten.

#ifndef Scene_3_hpp__cppwg_wrapper
#define Scene_3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_Scene_3_class(pybind11::module &m);
#endif // Scene_3_hpp__cppwg_wrapper
