// This file is auto-generated by cppwg; manual changes will be overwritten.

#ifndef Scene_2_hpp__cppwg_wrapper
#define Scene_2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_Scene_2_class(pybind11::module &m);
#endif // Scene_2_hpp__cppwg_wrapper
