// This file is automatically generated by cppwg.
// Do not modify this file directly.

#ifndef Shape_2_hpp__cppwg_wrapper
#define Shape_2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_Shape_2_class(pybind11::module &m);
#endif // Shape_2_hpp__cppwg_wrapper
