{% set version = "0.0.1" %}
{% set build = 0 %}

package:
  name: pycells
  version: {{ version }}

source:
  path: ..

build:
  number: {{ build }}

requirements:
  build:
    - cmake
    - ninja
    - pip
    - python
    - scikit-build
    - setuptools

  host:
    - mpi4py
    - mpich
    - petsc
    - petsc4py
    - python
    - vtk

test:
  imports:
    - pycells

about:
  license: BSD-3-Clause
