[build-system]
requires = ["setuptools", "wheel"]

[tool.black]
target-version = ["py38", "py39", "py310", "py311", "py312"]
extend-exclude = """
(
  ^/cppwg/templates/
  | _skbuild/
)
"""

[tool.isort]
profile = "black"
extend_skip = ["_skbuild"]
