{% set version = "0.0.1" %}
{% set build = 0 %}

package:
  name: pycells
  version: {{ version }}

source:
  path: ../..

build:
  number: {{ build }}

requirements:
  host:
    - mpi4py
    - openmpi
    - petsc
    - petsc4py
    - pip
    - python
    - scikit-build-core
    - vtk

test:
  imports:
    - pycells

about:
  license: BSD-3-Clause
