// This file is automatically generated by cppwg.
// Do not modify this file directly.

#ifndef Point_2_hpp__cppwg_wrapper
#define Point_2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_Point_2_class(pybind11::module &m);
#endif // Point_2_hpp__cppwg_wrapper
