[build-system]
requires = [
    "cmake",
    "ninja",
    "pybind11",
    "scikit-build",
    "setuptools",
]
build-backend = "setuptools.build_meta"

[tool.scikit-build]
cmake.build-type = "Release"
