// This file is automatically generated by cppwg.
// Do not modify this file directly.

#ifndef AbstractMesh_2_2_hpp__cppwg_wrapper
#define AbstractMesh_2_2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_AbstractMesh_2_2_class(pybind11::module &m);
#endif // AbstractMesh_2_2_hpp__cppwg_wrapper
