// This file is automatically generated by cppwg.
// Do not modify this file directly.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "wrapper_header_collection.cppwg.hpp"

#include "AbstractMesh_3_3.cppwg.hpp"

namespace py = pybind11;
typedef AbstractMesh<3, 3> AbstractMesh_3_3;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);

class AbstractMesh_3_3_Overrides : public AbstractMesh_3_3
{
public:
    using AbstractMesh_3_3::AbstractMesh;
    void Scale(double const factor) override
    {
        PYBIND11_OVERRIDE_PURE(
            void,
            AbstractMesh_3_3,
            Scale,
            factor);
    }
};

void register_AbstractMesh_3_3_class(py::module &m)
{
    py::class_<AbstractMesh_3_3, AbstractMesh_3_3_Overrides, std::shared_ptr<AbstractMesh_3_3>>(m, "AbstractMesh_3_3")
        .def(py::init<>())
        .def("GetIndex",
            (unsigned int(AbstractMesh_3_3::*)() const) &AbstractMesh_3_3::GetIndex,
            " ")
        .def("SetIndex",
            (void(AbstractMesh_3_3::*)(unsigned int)) &AbstractMesh_3_3::SetIndex,
            " ", py::arg("index"))
        .def("AddVertex",
            (void(AbstractMesh_3_3::*)(::Point<3>)) &AbstractMesh_3_3::AddVertex,
            " ", py::arg("vertex"))
        .def("Scale",
            (void(AbstractMesh_3_3::*)(double const)) &AbstractMesh_3_3::Scale,
            " ", py::arg("factor"))
    ;
}
