// This file is automatically generated by cppwg.
// Do not modify this file directly.

#ifndef AbstractMesh_3_3_hpp__cppwg_wrapper
#define AbstractMesh_3_3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_AbstractMesh_3_3_class(pybind11::module &m);
#endif // AbstractMesh_3_3_hpp__cppwg_wrapper
