// This file is automatically generated by cppwg.
// Do not modify this file directly.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "wrapper_header_collection.cppwg.hpp"

#include "ConcreteMesh_3.cppwg.hpp"

namespace py = pybind11;
typedef ConcreteMesh<3> ConcreteMesh_3;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);

class ConcreteMesh_3_Overrides : public ConcreteMesh_3
{
public:
    using ConcreteMesh_3::ConcreteMesh;
    void Scale(double const factor) override
    {
        PYBIND11_OVERRIDE(
            void,
            ConcreteMesh_3,
            Scale,
            factor);
    }
};

void register_ConcreteMesh_3_class(py::module &m)
{
    py::class_<ConcreteMesh_3, ConcreteMesh_3_Overrides, std::shared_ptr<ConcreteMesh_3>, AbstractMesh<3>>(m, "ConcreteMesh_3")
        .def(py::init<>())
        .def("Scale",
            (void(ConcreteMesh_3::*)(double const)) &ConcreteMesh_3::Scale,
            " ", py::arg("factor"))
    ;
}
