// This file is automatically generated by cppwg.
// Do not modify this file directly.

#ifndef ConcreteMesh_3_hpp__cppwg_wrapper
#define ConcreteMesh_3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_ConcreteMesh_3_class(pybind11::module &m);
#endif // ConcreteMesh_3_hpp__cppwg_wrapper
