// This file is automatically generated by cppwg.
// Do not modify this file directly.

#ifndef ConcreteMesh_2_hpp__cppwg_wrapper
#define ConcreteMesh_2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_ConcreteMesh_2_class(pybind11::module &m);
#endif // ConcreteMesh_2_hpp__cppwg_wrapper
