// This file is automatically generated by cppwg.
// Do not modify this file directly.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "wrapper_header_collection.hpp"

#include "MeshFactoryConcreteMesh3.cppwg.hpp"

namespace py = pybind11;
typedef MeshFactory<ConcreteMesh<3> > MeshFactoryConcreteMesh3;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);

void register_MeshFactoryConcreteMesh3_class(py::module &m){
py::class_<MeshFactoryConcreteMesh3  , std::shared_ptr<MeshFactoryConcreteMesh3 >   >(m, "MeshFactoryConcreteMesh3")
        .def(py::init< >())
    ;
}
