// This file is automatically generated by cppwg.
// Do not modify this file directly.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "wrapper_header_collection.hpp"

#include "MeshFactoryConcreteMesh2.cppwg.hpp"

namespace py = pybind11;
typedef MeshFactory<ConcreteMesh<2> > MeshFactoryConcreteMesh2;
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);

void register_MeshFactoryConcreteMesh2_class(py::module &m){
py::class_<MeshFactoryConcreteMesh2  , std::shared_ptr<MeshFactoryConcreteMesh2 >   >(m, "MeshFactoryConcreteMesh2")
        .def(py::init< >())
    ;
}
