// This file is automatically generated by cppwg.
// Do not modify this file directly.

#ifndef MeshFactoryConcreteMesh3_hpp__cppwg_wrapper
#define MeshFactoryConcreteMesh3_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_MeshFactoryConcreteMesh3_class(pybind11::module &m);
#endif // MeshFactoryConcreteMesh3_hpp__cppwg_wrapper
