// This file is automatically generated by cppwg.
// Do not modify this file directly.

#ifndef MeshFactoryConcreteMesh2_hpp__cppwg_wrapper
#define MeshFactoryConcreteMesh2_hpp__cppwg_wrapper

#include <pybind11/pybind11.h>

void register_MeshFactoryConcreteMesh2_class(pybind11::module &m);
#endif // MeshFactoryConcreteMesh2_hpp__cppwg_wrapper
