# For docs on config options, see examples/shapes/wrapper/package_info.yaml
name: pycells

smart_ptr_type: std::shared_ptr
pointer_call_policy: reference
reference_call_policy: reference_internal

common_include_file: False
source_includes:
  - <memory>

exclude_default_args: False

template_substitutions:
  - signature: <unsigned DIM>
    replacement: [[2], [3]]
  - signature: <unsigned SPACE_DIM>
    replacement: [[2], [3]]
  - signature: <unsigned ELEMENT_DIM, unsigned SPACE_DIM>
    replacement: [[2, 2], [3, 3]]
  - signature: <unsigned ELEMENT_DIM, unsigned SPACE_DIM=ELEMENT_DIM>
    replacement: [[2, 2], [3, 3]]

modules:
  - name: lib
    source_locations:
      - cell
      - mesh
      - utils
      - visualization

    classes:
      # cell
      - name: Cell

      # mesh
      - name: AbstractMesh
      - name: MeshFactory
        source_includes:
          - PottsMesh.hpp
        template_substitutions:
          - signature: <class MESH>
            replacement: [["PottsMesh<2>"], ["PottsMesh<3>"]]
      - name: Node
      - name: PottsMesh

      # utils
      - name: PetscUtils

      # visualization
      - name: Scene
        source_includes:
          - PybindVTKTypeCaster.h

prefix_text: |
  // This file is auto-generated by cppwg; manual changes will be overwritten.
