name: test-style

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"

concurrency:
  group: test-style-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install cmake

      - name: Install cppwg
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev]

      - name: Lint
        run: |
          python -m flake8 --version
          python -m flake8 .
