name: test-typecasters

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"

concurrency:
  group: build-and-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install \
            cmake \
            libpetsc-real3.15 \
            libpetsc-real3.15-dbg \
            libpetsc-real3.15-dev \
            libvtk9-dev \
            mpi-default-bin \
            mpi-default-dev \
            python3-mpi4py \
            python3-petsc4py-real3.15 \
            python3-vtk9 \
            vtk9

      - name: Build cells example
        run: |
          pip install --user --no-cache -v examples/cells

      - name: Test cells example
        run: |
          python -m unittest discover examples/cells/tests
