name: test-cells-ubuntu

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"

concurrency:
  group: test-cells-ubuntu-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-cells-ubuntu:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install \
            cmake \
            git \
            libpetsc-real3.15 \
            libpetsc-real3.15-dbg \
            libpetsc-real3.15-dev \
            libvtk9-dev \
            mpi-default-bin \
            mpi-default-dev \
            python3-mpi4py \
            python3-petsc4py-real3.15 \
            python3-vtk9 \
            vtk9

      - name: Install cppwg
        run: |
          python -m pip install --upgrade pip
          python -m pip install .

      - name: Configure
        run: |
          mkdir build && cd build
          cmake ..
        working-directory: examples/cells

      - name: Regenerate wrappers
        run: |
          rm -rf dynamic/wrappers
          cd build
          make pycells_wrappers
        working-directory: examples/cells

      - name: Check for changes
        run: |
          git diff --exit-code dynamic/wrappers
          grep "Unknown class" build/cppwg.log
        working-directory: examples/cells

      - name: Build
        run: python -m pip install -v .
        working-directory: examples/cells

      - name: Test
        run: python -m unittest discover -s tests
        working-directory: examples/cells
